-- ============================================================
-- Libro de Clases F2 — Importacion XLS 2026 (datos)
-- Generado desde preview_2026_corregido.json (dato canonico aprobado).
-- NO modifica el esquema F1. Transaccional y atomico.
-- Estudiantes: 231 | Matriculas: 233 (activo 217, retirado 16)
-- ============================================================
BEGIN;

-- Guarda anti-duplicado: aborta si ya existen matriculas 2026.
DO $$ BEGIN
  IF (SELECT count(*) FROM libro_matriculas m JOIN libro_anios a ON a.id=m.anio_id WHERE a.anio=2026) > 0 THEN
    RAISE EXCEPTION 'Importacion 2026 ya existe (hay matriculas). Abortando para no duplicar.';
  END IF;
END $$;

-- Staging temporal (una fila por matricula; se descarta al COMMIT).
CREATE TEMP TABLE _imp (tmp_id text, nombre text, apellido text, contexto text, posicion int, estado text) ON COMMIT DROP;
CREATE TEMP TABLE _map (tmp_id text PRIMARY KEY, est_id uuid DEFAULT gen_random_uuid(), nombre text, apellido text) ON COMMIT DROP;

INSERT INTO _imp (tmp_id, nombre, apellido, contexto, posicion, estado) VALUES
  ('e001','MAYLIN','ACIARES','PRIMERO',1,'activo'),
  ('e002','TRINIDAD','ARACENA','PRIMERO',2,'activo'),
  ('e003','ALEXANDER','BUSTAMANTE','PRIMERO',3,'activo'),
  ('e004','AMAYA','CAMPOS','PRIMERO',4,'activo'),
  ('e005','ESTEBAN','CARRASCO','PRIMERO',5,'activo'),
  ('e006','DIEGO','CEPEDA','PRIMERO',6,'activo'),
  ('e007','ASHLY','DIAZ','PRIMERO',7,'activo'),
  ('e008','IGNACIO','DIAZ','PRIMERO',8,'activo'),
  ('e009','SEBASTIAN','DONOSO','PRIMERO',9,'activo'),
  ('e010','VIOLETA','ESPINOZA','PRIMERO',10,'activo'),
  ('e011','ADHARA','ESPINOZA','PRIMERO',11,'activo'),
  ('e012','MATHEO','GRANADILLO','PRIMERO',12,'activo'),
  ('e013','VIOLETA','LOPEZ','PRIMERO',14,'activo'),
  ('e014','DAYANA','LOUIS','PRIMERO',15,'activo'),
  ('e015','TOMAS','MARTINEZ','PRIMERO',16,'activo'),
  ('e016','LEON','MENDEZ','PRIMERO',17,'activo'),
  ('e017','AGATHA','ORTEGA','PRIMERO',18,'activo'),
  ('e018','SANTIAGO','PACHECO','PRIMERO',19,'activo'),
  ('e019','ELIZ','PAZ','PRIMERO',20,'activo'),
  ('e020','MAXIMO','SANCHEZ','PRIMERO',21,'activo'),
  ('e021','MEIKO','SANTIBAÑEZ','PRIMERO',22,'activo'),
  ('e022','TOMAS','SOTO','PRIMERO',23,'activo'),
  ('e023','IKER','TORREBLANCA','PRIMERO',24,'activo'),
  ('e024','OSCAR','VERGARA','PRIMERO',25,'activo'),
  ('e025','OLIMPIA','BETANCOURT','SEGUNDO',1,'activo'),
  ('e026','MARCO','BRAVO','SEGUNDO',2,'activo'),
  ('e027','MAITHE','CATALAN','SEGUNDO',3,'activo'),
  ('e028','ANTONIA','CESAR','SEGUNDO',4,'activo'),
  ('e029','ISIDORA','CORIA','SEGUNDO',5,'activo'),
  ('e030','EMILIANO','CORTES','SEGUNDO',6,'activo'),
  ('e031','SOFÍA','CRISOSTO','SEGUNDO',7,'activo'),
  ('e032','AMANDA','FIGUEROA','SEGUNDO',8,'activo'),
  ('e033','KEÏSHA','FRANCOIS','SEGUNDO',9,'activo'),
  ('e034','RAFAEL','GARRIDO','SEGUNDO',10,'activo'),
  ('e035','ROXANA','GUTIERREZ','SEGUNDO',11,'activo'),
  ('e036','CHLÖE','HUECHE','SEGUNDO',12,'activo'),
  ('e037','AGUSTÍN','LARA','SEGUNDO',13,'activo'),
  ('e038','LUCIANA','LEIVA','SEGUNDO',14,'activo'),
  ('e039','VALENTÍN','LEYTON','SEGUNDO',15,'activo'),
  ('e040','JOSEFINA','LLANOS','SEGUNDO',16,'activo'),
  ('e041','SANTIAGO','LLANTEN','SEGUNDO',17,'activo'),
  ('e042','TAMARA','MUÑOZ','SEGUNDO',18,'activo'),
  ('e043','CLAUDIA','NARCISSE','SEGUNDO',19,'activo'),
  ('e044','MAITE','ORTIZ','SEGUNDO',20,'activo'),
  ('e045','NICOLÁS','OYARZÚN','SEGUNDO',21,'activo'),
  ('e046','ROSE','PARADA','SEGUNDO',22,'activo'),
  ('e047','ISABELLA','PEÑA','SEGUNDO',23,'activo'),
  ('e048','ELENA','PINO','SEGUNDO',24,'activo'),
  ('e049','FACUNDO','QUEZADA','SEGUNDO',25,'activo'),
  ('e050','ENZO','REYES','SEGUNDO',26,'activo'),
  ('e051','AGUSTINA','ROZAS','SEGUNDO',27,'activo'),
  ('e052','CRISTÓBAL','VALDES','SEGUNDO',28,'activo'),
  ('e053','JHON','VALENZUELA','SEGUNDO',29,'retirado'),
  ('e053','JHON','VALENZUELA','SEGUNDO',40,'activo'),
  ('e054','STEPHANIE','VARGAS','SEGUNDO',30,'activo'),
  ('e055','MILLARAY','VARGAS','SEGUNDO',31,'activo'),
  ('e056','MAITE','VARGAS','SEGUNDO',32,'activo'),
  ('e057','MATÍAS','VILLALON','SEGUNDO',33,'activo'),
  ('e058','ELIZA','ROJAS','SEGUNDO',34,'retirado'),
  ('e059','ANARA','BRAVO','SEGUNDO',35,'activo'),
  ('e060','SERGIO','LAMANA','SEGUNDO',36,'activo'),
  ('e061','DAFNE','CARRILLO','SEGUNDO',37,'retirado'),
  ('e062','ANGEL','CARRILLO','SEGUNDO',38,'activo'),
  ('e063','MATÍAS','VERGARA','SEGUNDO',39,'activo'),
  ('e064','DARIEL','ACIARES','TERCERO',1,'activo'),
  ('e065','FLORENCIA','ASTORGA','TERCERO',2,'activo'),
  ('e066','MATEO','BASCUR','TERCERO',3,'activo'),
  ('e067','CHRISTIAN','CÁDIZ','TERCERO',4,'activo'),
  ('e068','AHINARA','CAMPOS','TERCERO',5,'activo'),
  ('e069','STEFANIA','DÍAZ','TERCERO',6,'activo'),
  ('e070','JOEL','ESPINOSA','TERCERO',7,'activo'),
  ('e071','NELSON','HANS','TERCERO',8,'activo'),
  ('e072','VICENTE','LEÓN','TERCERO',9,'activo'),
  ('e073','ANGELA','MANSILLA','TERCERO',10,'activo'),
  ('e074','PAZCAL','MENDOZA','TERCERO',11,'activo'),
  ('e075','EMMA','MONTERO','TERCERO',12,'activo'),
  ('e076','KATALINA','MUÑOZ','TERCERO',13,'activo'),
  ('e077','DAMIAN','MURA','TERCERO',14,'retirado'),
  ('e077','DAMIAN','MURA','TERCERO',28,'activo'),
  ('e078','ABIGAIL','ORTIZ','TERCERO',15,'activo'),
  ('e079','AMANDA','ORTIZ','TERCERO',16,'retirado'),
  ('e080','EMILIANO','OSORIO','TERCERO',17,'activo'),
  ('e081','ALAN','QUINTERO','TERCERO',18,'activo'),
  ('e082','GUSTAVO','RODRÍGUEZ','TERCERO',19,'activo'),
  ('e083','ALEJANDRO','ROMERO','TERCERO',20,'activo'),
  ('e084','ADELAINE','RUBIO','TERCERO',21,'activo'),
  ('e085','AGUSTINA','RUBIO','TERCERO',22,'activo'),
  ('e086','LISANDRA','RUIZ','TERCERO',23,'activo'),
  ('e087','MARTÍN','SANCHEZ','TERCERO',24,'activo'),
  ('e088','FELIPE','TOBAR','TERCERO',25,'retirado'),
  ('e089','PABLO','VALENZUELA','TERCERO',26,'activo'),
  ('e090','AGUSTÍN','SCHAAF','TERCERO',27,'activo'),
  ('e091','NOEMÍ','ARAVENA','TERCERO',29,'activo'),
  ('e092','EMILIANO','ALVARADO','CUARTO',1,'activo'),
  ('e093','GASPAR','AVILEZ','CUARTO',2,'retirado'),
  ('e094','PERCIVAL','BETANCOURT','CUARTO',3,'activo'),
  ('e095','RAÚL','BRIZUELA','CUARTO',4,'activo'),
  ('e096','VICTORIA','CAMPOS','CUARTO',5,'activo'),
  ('e097','TOMÁS','FUENTES','CUARTO',6,'activo'),
  ('e098','ARAMÍS','GODOY','CUARTO',7,'activo'),
  ('e099','ANDRUW','HERNANDEZ','CUARTO',8,'activo'),
  ('e100','FELIPE','JARA','CUARTO',9,'activo'),
  ('e101','THOMAS','LAGOS','CUARTO',10,'activo'),
  ('e102','KRIS','LAUREANO','CUARTO',11,'activo'),
  ('e103','JAVIER','LLANOS','CUARTO',12,'activo'),
  ('e104','SARAI','MONDACA','CUARTO',13,'activo'),
  ('e105','MARIANA','MORALES','CUARTO',14,'activo'),
  ('e106','CLAUDIO','NAVARRETE','CUARTO',15,'activo'),
  ('e107','IRWIN','OJEDA','CUARTO',16,'activo'),
  ('e108','EDUARDO','OYARZÚN','CUARTO',17,'activo'),
  ('e109','ROOD','PRINTEMPS','CUARTO',18,'activo'),
  ('e110','MARTINA','RAMÍREZ','CUARTO',19,'activo'),
  ('e111','FLORENCIA','REYES','CUARTO',20,'activo'),
  ('e112','ALLISON','SÁEZ','CUARTO',21,'activo'),
  ('e113','EMILIANO','SALAS','CUARTO',22,'activo'),
  ('e114','DIEGO','SILVA','CUARTO',23,'activo'),
  ('e115','BALTAZAR','SOTO','CUARTO',24,'activo'),
  ('e116','RAYÉN','VARGAS','CUARTO',25,'activo'),
  ('e117','MATÍAS','LAMANA','CUARTO',26,'activo'),
  ('e118','TOMÁS','MUÑOZ','CUARTO',27,'activo'),
  ('e119','RENATA','AGUILAR','QUINTO',1,'activo'),
  ('e120','SALVADOR','ARAUJO','QUINTO',2,'activo'),
  ('e121','ÁMBAR','ARAYA','QUINTO',3,'activo'),
  ('e122','MARTÍN','ARAYA','QUINTO',4,'activo'),
  ('e123','AARÓN','AYALA','QUINTO',5,'activo'),
  ('e124','TABATHA','CHAPARRO','QUINTO',6,'activo'),
  ('e125','ISAIAS','CORNEJO','QUINTO',7,'activo'),
  ('e126','TRINIDAD','CRISOSTO','QUINTO',8,'activo'),
  ('e127','HUGO','DELGADO','QUINTO',9,'activo'),
  ('e128','COLOMBA','ESPINOZA','QUINTO',10,'retirado'),
  ('e129','MATILDA','GALLEGUILLOS','QUINTO',11,'activo'),
  ('e130','EMILY','GONZÁLEZ','QUINTO',12,'activo'),
  ('e131','SOFÍA','HERRERA','QUINTO',13,'activo'),
  ('e132','LUCIANA','HOYOS','QUINTO',14,'activo'),
  ('e133','MIZHAEL','LAUREANO','QUINTO',15,'activo'),
  ('e134','NICOLÁS','LUENGO','QUINTO',16,'activo'),
  ('e135','TRINIDAD','MÉNDEZ','QUINTO',17,'activo'),
  ('e136','BALTAZAR','MORENO','QUINTO',18,'activo'),
  ('e137','ERIC','MUÑOZ','QUINTO',19,'activo'),
  ('e138','FRANCISCO','MUÑOZ','QUINTO',20,'activo'),
  ('e139','MARÍA JESÚS','PINO','QUINTO',21,'activo'),
  ('e140','MICHEL','SALAS','QUINTO',22,'activo'),
  ('e141','ANTHONY','SÁNCHEZ','QUINTO',23,'activo'),
  ('e142','BENJAMÍN','SANDOVAL','QUINTO',24,'activo'),
  ('e143','SEBASTIAN','SUAREZ','QUINTO',25,'activo'),
  ('e144','AYLEN','SUAZO','QUINTO',26,'activo'),
  ('e145','ABRAHAM','TRONCOSO','QUINTO',27,'activo'),
  ('e146','ÓSCAR','URIBE','QUINTO',28,'activo'),
  ('e147','ROSARIO','VALDÉS','QUINTO',29,'activo'),
  ('e148','HADASA','VALENZUELA','QUINTO',30,'activo'),
  ('e149','JUAN','VEGA','QUINTO',31,'activo'),
  ('e150','ÁMBAR','VILLARREAL','QUINTO',32,'activo'),
  ('e151','EMILIA','YÁÑEZ','QUINTO',33,'activo'),
  ('e152','FERNANDO','ZÚÑIGA','QUINTO',34,'activo'),
  ('e153','MAXIMILIANO','PARRA','QUINTO',35,'retirado'),
  ('e154','JULIÁN','ROJAS','QUINTO',36,'retirado'),
  ('e155','DAFNE','CARRILLO','QUINTO',37,'retirado'),
  ('e156','BRUNO','ARELLANO','SEXTO',1,'activo'),
  ('e157','AMANDA','AYALA','SEXTO',2,'activo'),
  ('e158','ISAAC','BAHAMONDES','SEXTO',3,'activo'),
  ('e159','MÁXIMO','BRICEÑO','SEXTO',4,'activo'),
  ('e160','VIOLETA','BUSTOS','SEXTO',5,'activo'),
  ('e161','JEAN','CÁCERES','SEXTO',6,'activo'),
  ('e162','CONSTANZA','CARTER','SEXTO',7,'activo'),
  ('e163','LEONOR','CONTRERAS','SEXTO',8,'activo'),
  ('e164','CAMILA','DÍAZ','SEXTO',9,'activo'),
  ('e165','JOSUE','DONOSO','SEXTO',10,'retirado'),
  ('e166','DARINKA','ESCOBAR','SEXTO',11,'activo'),
  ('e167','ASHLEY','FUENTES','SEXTO',12,'activo'),
  ('e168','IGNACIO','GALINDO','SEXTO',13,'activo'),
  ('e169','MÁXIMO','GANGA','SEXTO',14,'activo'),
  ('e170','AARON','HERNANDEZ','SEXTO',15,'activo'),
  ('e171','DOMINIQUE','HERNANDO','SEXTO',16,'activo'),
  ('e172','CONSTANZA','HUENUMÁN','SEXTO',17,'activo'),
  ('e173','THIARE','IBACACHE','SEXTO',18,'activo'),
  ('e174','MAITE','JARA','SEXTO',19,'activo'),
  ('e175','AMARAL','LIZAMA','SEXTO',20,'activo'),
  ('e176','ALISE','LÓPEZ','SEXTO',21,'activo'),
  ('e177','ELÍAS','MARQUINA','SEXTO',22,'activo'),
  ('e178','EMILY','MARTÍNEZ','SEXTO',23,'activo'),
  ('e179','SANTIAGO','MOSQUERA','SEXTO',24,'activo'),
  ('e180','FÁTIMA','MUÑOZ','SEXTO',25,'activo'),
  ('e181','MARTINA','PAREDES','SEXTO',26,'activo'),
  ('e182','GÉNESIS','PAZ','SEXTO',27,'activo'),
  ('e183','ALEXANDER','PEÑA','SEXTO',28,'activo'),
  ('e184','AGUSTINA','RAMÍREZ','SEXTO',29,'activo'),
  ('e185','VALENTÍN','RUIZ','SEXTO',30,'activo'),
  ('e186','ISIDORA','RUZ','SEXTO',31,'activo'),
  ('e187','IGNACIA','TAPIA','SEXTO',32,'activo'),
  ('e188','PASCAL','TAPIA','SEXTO',33,'activo'),
  ('e189','FELIPE','TORRES','SEXTO',34,'activo'),
  ('e190','AMARO','VALDIVIA','SEXTO',35,'retirado'),
  ('e191','FERNANDA','VENEGAS','SEXTO',36,'activo'),
  ('e192','CRISTÓBAL','VERGARA','SEXTO',37,'activo'),
  ('e193','MADELEYN','VERGARA','SEXTO',38,'activo'),
  ('e194','SOPHIE','AGUILAR','SEPTIMO',1,'activo'),
  ('e195','VICTORIA','CONTRERAS','SEPTIMO',2,'activo'),
  ('e196','ANAÍS','CORTÉS','SEPTIMO',3,'activo'),
  ('e197','ANELEY','DÍAZ','SEPTIMO',4,'activo'),
  ('e198','AGUSTINA','ESPINOZA','SEPTIMO',5,'retirado'),
  ('e199','GIANELA','FAJARDO','SEPTIMO',6,'activo'),
  ('e200','VALENTINA','FARFÁN','SEPTIMO',7,'activo'),
  ('e201','CAMILA','FUENTES','SEPTIMO',8,'activo'),
  ('e202','SAMIRA','HUENCHÚN','SEPTIMO',9,'activo'),
  ('e203','ARACELLY','JARA','SEPTIMO',10,'activo'),
  ('e204','EMILY','LAGOS','SEPTIMO',11,'activo'),
  ('e205','GENESIS','LAUREANO','SEPTIMO',12,'activo'),
  ('e206','SOFÍA','LÓPEZ','SEPTIMO',13,'activo'),
  ('e207','DANAE','MACHUCA','SEPTIMO',14,'activo'),
  ('e208','PASCALL','MOYA','SEPTIMO',15,'activo'),
  ('e209','LAURA','OYARZÚN','SEPTIMO',16,'activo'),
  ('e210','CHANNEL','PALMA','SEPTIMO',17,'activo'),
  ('e211','MARTINA','RAMOS','SEPTIMO',18,'activo'),
  ('e212','CAMILA','RODRÍGUEZ','SEPTIMO',19,'activo'),
  ('e213','SOFIA','SUAREZ','SEPTIMO',20,'activo'),
  ('e214','AGUSTINA','TORRES','SEPTIMO',21,'activo'),
  ('e215','SOFÍA','VALENZUELA','SEPTIMO',22,'activo'),
  ('e216','EMILIE','AGUILAR','OCTAVO',1,'activo'),
  ('e217','ANTONELLA','ATENAS','OCTAVO',2,'activo'),
  ('e218','ISIDORA','CARREÑO','OCTAVO',3,'retirado'),
  ('e219','CESIA','DONOSO','OCTAVO',4,'retirado'),
  ('e220','EMILY','JIMÉNEZ','OCTAVO',5,'activo'),
  ('e221','FERNANDA','MORENO','OCTAVO',6,'activo'),
  ('e222','CATALINA','NAHUELHUEIQUE','OCTAVO',7,'activo'),
  ('e223','JOSEFA','PONCE','OCTAVO',8,'activo'),
  ('e224','ANGELES','RIOS','OCTAVO',9,'activo'),
  ('e225','VALENTINA','ROBLES','OCTAVO',10,'activo'),
  ('e226','EIMILY','ROJAS','OCTAVO',11,'activo'),
  ('e227','MIA','SAAVEDRA','OCTAVO',12,'activo'),
  ('e228','ORIANA','SEPÚLVEDA','OCTAVO',13,'activo'),
  ('e229','FERNANDA','SOTO','OCTAVO',14,'activo'),
  ('e230','MERY','VASQUEZ','OCTAVO',15,'activo'),
  ('e231','FERNANDA','VILCA','OCTAVO',16,'activo');

-- Un estudiante por tmp_id (los tmp_id con 2 matriculas producen 1 solo estudiante).
INSERT INTO _map (tmp_id, nombre, apellido)
  SELECT DISTINCT tmp_id, nombre, apellido FROM _imp;

-- Estudiantes reales (id explicito desde el mapa).
INSERT INTO libro_estudiantes (id, nombre, apellido)
  SELECT est_id, nombre, apellido FROM _map;

-- Matriculas: enlaza cada fila de _imp a su estudiante, al anio 2026 y al contexto de curso.
INSERT INTO libro_matriculas (estudiante_id, anio_id, contexto_id, posicion, estado, fecha_ingreso, fecha_retiro)
  SELECT m.est_id, a.id, c.id, i.posicion, i.estado, NULL, NULL
  FROM _imp i
  JOIN _map m USING (tmp_id)
  JOIN libro_anios a ON a.anio = 2026
  JOIN contextos c ON c.nombre = i.contexto AND c.tipo = 'curso';

-- Asercion de conteos: si algo no cuadra, RAISE -> rollback de toda la transaccion.
DO $$ DECLARE ne int; nm int; na int; nr int; BEGIN
  SELECT count(*) INTO ne FROM libro_estudiantes;
  SELECT count(*) INTO nm FROM libro_matriculas m JOIN libro_anios a ON a.id=m.anio_id WHERE a.anio=2026;
  SELECT count(*) INTO na FROM libro_matriculas m JOIN libro_anios a ON a.id=m.anio_id WHERE a.anio=2026 AND m.estado='activo';
  SELECT count(*) INTO nr FROM libro_matriculas m JOIN libro_anios a ON a.id=m.anio_id WHERE a.anio=2026 AND m.estado='retirado';
  IF ne <> 231 THEN RAISE EXCEPTION 'estudiantes=% (esperado 231)', ne; END IF;
  IF nm <> 233 THEN RAISE EXCEPTION 'matriculas=% (esperado 233)', nm; END IF;
  IF na <> 217 THEN RAISE EXCEPTION 'activo=% (esperado 217)', na; END IF;
  IF nr <> 16  THEN RAISE EXCEPTION 'retirado=% (esperado 16)', nr; END IF;
END $$;

COMMIT;
